<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\BasicStuff.Models\BasicStuff.Models.csproj" />
	  <ProjectReference Include="..\BasicStuff.Domain\BasicStuff.Domain.csproj" />
  </ItemGroup>

</Project>
